{% set name = "sphinx-comments" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx-comments-{{ version }}.tar.gz
  sha256: 00170afff27019fad08e421da1ae49c681831fb2759786f07c826e89ac94cf21

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=1.8

test:
  imports:
    - sphinx_comments
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/sphinx-comments
  summary: Add comments and annotation to your documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - anirrudh
    - chrisjsewell
